### ISSUE TITLE
Todoist showing completed tasks from last year

### ISSUE THREAD

**Issue by mattjastremski** [dakboard/bugs#27]
Todoist is showing completed tasks from a long time ago. I can only get them to go away if I go into Todoist and delete the completed items.

**Comment by cocarrig** [comment]
Hi,

It is possible the todoist response is will including the irrelevant response in the call to their service.  In this case it can only be fixed by manually deleting as you have indicated.

If you are still experiencing this issue on DAKboard please reach out to support@dakboard.com.  A member of support team can gather additional detail and compose a bug issue or help to identify a configuration issue by working with you on your account.
