### ISSUE TITLE
Calendar not updating

### ISSUE THREAD

**Issue by VinnCecil** [dakboard/bugs#4]
My Dakboard display is powered by a Raspberry Pi Zero W. I have made sure everything is updated but the calendar stays stuck on the same day and the weather does also. The time and date on top of the layout is correct but the actual weather and calendar will not update when adding events or when its a new day. I restarted my calendar Sunday afternoon and now its Monday and still showing as Sunday. Can someone please look into this and help me figure this out?

**Comment by cocarrig** [comment]
Hi,

We have not tested DAKboard OS on Pi Zero and do not recommend its use due to its limited hardware, but some users have found a few steps to improve performance that we have documented here:
https://dakboard.freshdesk.com/support/solutions/articles/35000150982-dakboard-os-on-a-raspberry-pi-zero

If you are still experiencing issue please reach out to contact@dakboard.com.
